services:
  app:
    build: .
    container_name: class-management
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules  # 이 줄이 node_modules 오염 방지
    networks:
      - backend
    command: node server.js
    restart: always

  db:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    env_file:
      - .env.production
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
